# HYPERNETS_TOOLS=~/hypernets_tools

bold=$(tput bold)
red=$(tput setaf 9)
green=$(tput setaf 10)
yellow=$(tput setaf 11)
reset=$(tput sgr0)

# print help
commands() {
	dupcc=$(df -kh . | tail -n1 | awk '{print $5}') >/dev/null 2>&1
	duchk="${dupcc//%}"

	echo
	if [[ $duchk -ge 80 ]]
	then
		echo "   Hypstar Commands    ${red}   DISK USAGE: $dupcc${reset}"
	else
		echo "   Hypstar Commands       DISK USAGE: $dupcc"
	fi
	echo "${yellow} ********************" 
	echo "${yellow} commands	${reset}to see this list"
	#echo "${yellow} guide  	${reset}Hypstar cheat sheet "
	#echo "${yellow} schedule	${reset}view/adjust yocto schedules 1 & 2     Set yocto rtc time"
	echo "${yellow} relay   	${reset}returns states or with args sets relay n state    eg: relay 5 on   relay 6 off ..."
	echo "${yellow} pt		${reset}Pan/Tilt position   or move with args:  pt 90 34    see pt -h for more"
	#echo "${yellow} vm    	${reset}vm on   vm off "
	echo "${yellow} now    	${reset}present status of: clock, meteo, rain, GPS, supply, wakeup"
	#echo "${yellow} webpic  	${reset}takes  webcam photos, Photos stored in ~/hypernets_tools/OTHER/Web-site~sky/  & Server/Sitename/ "
	#echo "${yellow} hypypic  	${reset}takes photo from hypstar camera. Photos stored in  ~/hypypics/   & Server/Sitename/ "
	#echo "${yellow} level    	${reset}boom leveling assistant "
	echo "${yellow} test-env  	${reset}displays hypstar test_env once"
	echo "${yellow} test-env-live	${reset}displays hypstar test_env live"
	echo "${yellow} status  	${reset}sudo systemctl status hypernets-sequence"
	echo "${yellow} kill-service	${reset}kill hypernets-sequence service without going to sleep"
	echo "${yellow} journal  	${reset}journalctl -b -u hypernets-sequence -e (journal -f to follow)"
	#echo "${yellow} slog  	${reset}displays a summary log & index to logs of prevoius runs "
	#echo "${yellow} portal  	${reset}makes a portal via ~/Portal folder to Server/Sitename/ "
	echo "${yellow} gui		${reset}python -m hypernets.gui (if screen attached)"
	#echo "${yellow} cp2server	 ${reset}                 ./utils/hello_server.sh   copy sequence data back to NPL server "
	echo "${yellow} runseq	 	${reset}./utils/run_service.sh    run a sequence"
	echo "${yellow} yapo		${reset}yocto auto-power-off.   yapo stop   to disable, see yapo -h for more"
	echo "${yellow} goto-sleep	${reset}power off and send yocto to sleep if wakeup is scheduled"
	echo
} # commands()


# present status of: clock, meteo, rain, GPS, supply, wakeup
now() (
	cd $HYPERNETS_TOOLS

	# check if Yocto command line API is installed
	if [[ $(command -v YRealTimeClock) ]]; then
		yocto_api_installed=1

		source utils/configparser.sh
		yocto=$(parse_config "yocto_prefix2" config_static.ini)
	else
		yocto_api_installed=0
	fi

	echo "System time is $(date '+%Y/%m/%d %H:%M:%S %Z')"

	# get yocto time
	if [[ $yocto_api_installed ]]; then
		yocto_time=$(YRealTimeClock -f '[result]' -r 127.0.0.1 $yocto get_dateTime)
		yocto_offset=$(YRealTimeClock -f '[result]' -r 127.0.0.1 $yocto get_utcOffset)

		if [ $yocto_offset = 0 ]; then
			utc_offset=""
		else
			utc_offset=$(printf "%+d" $(($yocto_offset/3600)))
		fi

		if [ $yocto_offset = 0 ]; then
			echo "Yocto time is  $yocto_time UTC$utc_offset"
		else
			echo "Yocto time is  $yocto_time UTC$utc_offset (UTC offset is $yocto_offset s)"
		fi
	fi

	echo "Yocto meteo: $(python -m hypernets.yocto.meteo | sed -E -e 's/\(|\)|\[|\]|\"//g' | sed -e "s/'//2g" | sed '-es/,//'{7..1..2})"

	if [ ! -f hypernets/rain_sensor/rain_sensor ]; then
		(cd hypernets/rain_sensor/ && make)
	fi

	set +e
	relay_on="$(python -m hypernets.yocto.relay -g -n4 2>&1 | grep -c True)"
	set -e

	# rain sensor relay is off, switch on
	if [ $relay_on = 0 ]; then
		python -m hypernets.yocto.relay -son -n4
		sleep 1
	fi

	hypernets/rain_sensor/rain_sensor

	# restore rain sensor relay state
	if [ $relay_on = 0 ]; then
		python -m hypernets.yocto.relay -soff -n4
	fi

	echo "Yocto GPS: $(python -m hypernets.yocto.gps)"
	echo "Supply voltage is $(python -m hypernets.yocto.voltage) V"
	echo "Wake up reason is $(python -m hypernets.yocto.wakeupreason)"

	# get watchdog and wakeup timers
	if [[ $yocto_api_installed ]]; then
		next_wakeup_timestamp=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_nextWakeUp|sed -e 's/[[:space:]].*//')
		max_wakeup_time=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_powerDuration)
		sleep_countdown=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_sleepCountdown)

		if [ $max_wakeup_time = 0 ]; then
			echo "${red}Yocto Auto-Power-Off is disabled${reset}"
		else
			echo "${yellow}Yocto Auto-Power-Off set to $max_wakeup_time s, ${red}powering off in $sleep_countdown s${reset}"
		fi

		if [ $next_wakeup_timestamp = 0 ]; then
			echo "${red}Yocto scheduled wakeup is disabled${reset}"
		else
			delta=$(( $next_wakeup_timestamp - $yocto_offset - $(date -u +%s) ))
			echo "${yellow}Next Yocto wakeup is scheduled on $(date -d @$next_wakeup_timestamp '+%Y/%m/%d %H:%M:%S') UTC$utc_offset (in $delta s)${reset}"
		fi
	fi
) #now()


# returns states or with args sets relay n state    eg: relay 5 on   relay 6 off ...
relay() (
	cd $HYPERNETS_TOOLS

	if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
		echo
		echo "Yocto relays"
		echo "relay [-h|--help] [relay_number on|off]"
		echo "relay -h      print this help"
		echo "relay         print current relay states"
		echo "relay 3 on    switch on HYPSTAR relay #3"
		echo "relay 3 off   switch off HYPSTAR relay #3"
		echo
		exit 1
	fi

	if [[ $2 == "on" ]] || [[ $2 == "off" ]]; then
		python -m hypernets.yocto.relay -s $2 -n $1
	fi

	echo -e "PC\tPT\tHYP\tRS\tCAM1\tCAM2"
	echo -e  "1\t2\t3\t4\t5\t6"
	python -m hypernets.yocto.relay -g -n1 -n2 -n3 -n4 -n5 -n6 2>&1 | egrep -o  "(True|False)" | sed -e "s/False/${red}OFF${reset}/g;s/True/${green}ON${reset}/g" | paste -s
) # relay()


# displays hypstar test_env once
test-env() (
	cd $HYPERNETS_TOOLS

	set +e
	relay_on=$(python -m hypernets.yocto.relay -g -n3 2>&1 | grep -c True)
	set -e

	if [ $relay_on = 0 ]; then
		echo "${red}Radiometer relay #3 is off${reset}"
		exit
	fi

	cd hypernets/hypstar/libhypstar/ 

	if [ -f build/test_env ]; then
		build/test_env
	else
		make test_env
	fi
) # test-env()


# displays hypstar test_env live
test-env-live() (
	cd $HYPERNETS_TOOLS

	set +e
	relay_on=$(python -m hypernets.yocto.relay -g -n3 2>&1 | grep -c True)
	set -e

	if [ $relay_on = 0 ]; then
		echo "${red}Radiometer relay #3 is off${reset}"
		exit
	fi

	cd hypernets/hypstar/libhypstar/ 

	if [ ! -f build/test_env ]; then
		make test_env
	fi

	watch -n 5 build/test_env
) # test-env-live()


# power off and send yocto to sleep if wakeup is scheduled
goto-sleep() (
	cd $HYPERNETS_TOOLS

	# dummy sudo for quick elevation of privileges later during poweroff
	# yocto sleep timer is only 10 s
	sudo sleep 0

	# forced sleep
	if [[ ${1-} == "--force" ]]; then
		echo "${red}Forcing sleep${reset}"
		force="--force"
	fi

	set +e
    python -m hypernets.yocto.sleep_monitor ${force-}
	yocto_sleep=$?
	set -e

	if [[ $yocto_sleep -eq 0 ]]; then
		# All OK, shuttig down
		echo "${red}Powering off${reset}"
		sleep 1
		sudo poweroff
	fi

	# Something went wrong
	if [[ $yocto_sleep -eq 1 ]]; then
		echo "${red}Yocto unreachable !!${reset}"
	elif [[ $yocto_sleep -eq 255 ]]; then
		echo "${red}Yocto scheduled wakeup is disabled!!!"
		echo "${bold}Waking up is possible ONLY by manually pressing 'WAKE' button!!!${reset}"
		echo
		echo "${red}Use 'goto-sleep --force' to force sleep${reset}"
	fi
) # goto-sleep()


## Yocto-Auto-Power-Off configuration
yapo() (
	cd $HYPERNETS_TOOLS

	yoption=$1
	new_max_runtime=$2

	# check if Yocto command line API is installed
	if [[ $(command -v YWakeUpMonitor) ]]; then
		source utils/configparser.sh
		yocto=$(parse_config "yocto_prefix2" config_static.ini)
	else
		echo "${red}Yocto API is not installed${reset}"
		exit -1
	fi

	if [[ $yoption == "-h" ]] || [[ $yoption == "--help" ]]; then
		echo
		echo "Yocto~Auto~Power~Off"
		echo "yapo			without options returns the time in seconds until yocto turns PC power off"
		echo "     set 180->99999	sets yocto max run time (in secs)   ${red}(3 minutes minimum!)${reset}"
		echo "     stop		prevents yocto powering off for   infinity..."
		echo "     reset		resets the yocto power-off countdown timer"
		echo "eg:  yapo set 720      yapo stop       yapo reset"
		echo
		exit 
	fi
	
	max_wakeup_time=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_powerDuration)
	next_wakeup_timestamp=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_nextWakeUp|sed -e 's/[[:space:]].*//')
	sleep_countdown=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_sleepCountdown)
	yocto_offset=$(YRealTimeClock -f '[result]' -r 127.0.0.1 $yocto get_utcOffset)
		
	if [[ $yoption == "" ]]; then ######## display yocto-auto-power-off status ###############
		if [[ $max_wakeup_time -eq "0" ]]; then
			echo "${yellow}Yocto Auto-Power-Off is ${red}disabled! ${yellow}PC will run for ${red}infinity...${reset}"
			echo "Enter:   yapo set    to re-enable yocto-auto-power-off"
			exit 0
		else 
			echo "${yellow}Yocto Auto-Power-Off set to $max_wakeup_time s, ${red}powering off in $sleep_countdown s${reset}"
			if [ $yocto_offset = 0 ]; then
				utc_offset=""
			else
				utc_offset=$(printf "%+d" $(($yocto_offset/3600)))
			fi
			
			if [ $next_wakeup_timestamp = 0 ]; then
				echo "${red}Yocto scheduled wakeup is disabled${reset}"
			else
				delta=$(( $next_wakeup_timestamp - $yocto_offset - $(date -u +%s) ))
				echo "${yellow}Next Yocto wakeup is scheduled on $(date -d @$next_wakeup_timestamp '+%Y/%m/%d %H:%M:%S') UTC$utc_offset (in $delta s)${reset}"
			fi

			echo "Enter:   yapo stop    to disable yocto-auto-power-off"
			echo "         yapo reset   to reset the countdown timer"
		fi
	elif [[ $yoption == "stop" ]]; then ############ disable yocto-auto-power-off ################
		if [[ $max_wakeup_time -ne "0" ]]; then
			echo "${yellow}Auto-Power-Off setting was $max_wakeup_time s${reset}"

			YWakeUpMonitor -r 127.0.0.1 -s $yocto set_powerDuration 0 >/dev/null 2>&1
			echo "${red}Yocto Auto-Power-Off is now disabled${reset}"
		else
			echo "${yellow}Yocto Auto-Power-Off was already ${red}disabled${reset}"
		fi
	elif [[ $yoption == "set" ]]; then #################### Set max run time ##########################
		# check is not empty & is a number
		set +eu
		[ -n "$new_max_runtime" ] && [ "$new_max_runtime" -eq "$new_max_runtime" ] 2>/dev/null
		if [ $? -ne 0 ]; then
			echo "${red}Invalid input, yapo set requires max runtime in seconds as second parameter.${reset}"
			echo
			exit -1
		fi
		set -eu

		if (( $new_max_runtime < 180 )); then  # LIMIT YOCTO MAXRUNTIME TO NO LESS THAN 3 MINS 
			new_max_runtime=180
			echo "${red}Requested runtime limit is too short, using minimum allowed value ${new_max_runtime} s${reset}"
		fi

		YWakeUpMonitor -r 127.0.0.1 -s $yocto set_powerDuration $new_max_runtime >/dev/null 2>&1
		set_max_wakeup_time=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_powerDuration)
		echo "${yellow}Auto-Power-Off set to power off after ${red}$set_max_wakeup_time seconds${reset}"
	elif [[ $yoption == "reset" ]]; then #################### Reset shutdown counter max run time ##########################
		if [[ $max_wakeup_time -ne "0" ]]; then
			YWakeUpMonitor -r 127.0.0.1 $yocto set_sleepCountdown $max_wakeup_time >/dev/null 2>&1
			new_sleep_countdown=$(YWakeUpMonitor -f '[result]' -r 127.0.0.1 $yocto get_sleepCountdown)
			echo "${yellow}Auto-Power-Off reset to power off after ${red}$new_sleep_countdown seconds${reset}"
		else
			echo "${yellow}Yocto Auto-Power-Off was already ${red}disabled${reset}"
		fi
	else
		echo "Unknown option, run yapo -h for help"
	fi
) # yapo()


## helper functions for converting between absolute and relative positions
## force to 0...360 range
_pt_abs2rel_pan() {
	if [[ $reverse_tilt == "yes" ]]; then
		printf "%.1f" $( bc <<< "($1 - $offset_pan - 180 + 36000) % 360" )
	else
		printf "%.1f" $( bc <<< "($1 + $offset_pan + 36000) % 360" )
	fi
}

_pt_abs2rel_tilt() {
	if [[ $reverse_tilt == "yes" ]]; then
		printf "%.1f" $( bc <<< "(- $1 - $offset_tilt + 36000) % 360" )
	else
		printf "%.1f" $( bc <<< "($1 + $offset_tilt + 36000) % 360" )
	fi
}

_pt_rel2abs_pan() {
	if [[ $reverse_tilt == "yes" ]]; then
		printf "%.1f" $( bc <<< "($1 + $offset_pan + 180 + 36000) % 360" )
	else
		printf "%.1f" $( bc <<< "($1 - $offset_pan + 36000) % 360" )
	fi
}

_pt_rel2abs_tilt() {
	if [[ $reverse_tilt == "yes" ]]; then
		printf "%.1f" $( bc <<< "(- ($1 + $offset_tilt) + 36000) % 360" )
	else
		printf "%.1f" $( bc <<< "($1 - $offset_tilt + 36000) % 360" )
	fi
}


## Pan-Tilt control
pt() (
	cd $HYPERNETS_TOOLS

	if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
		echo
		echo "  Pan-tilt control"
		echo "********************"
		echo "pt [-h|--help] [abs] [new_pan new_tilt]"
		echo "pt                        without options returns the current pan-tilt position"
		echo "   new_pan new_tilt       move pan-tilt to new position while accounting for the offsets in config_dynamic.ini"
		echo "   abs new_pan new_tilt   move pan-tilt to new absolute position"
		echo
		echo "use x as new value for the axis that has to stay in the current position"
		echo "eg:  pt 270 90      pt abs 270 90      pt x 0"
		echo
		exit 
	fi

	# use absolute position
	if [[ $1 == "abs" ]]; then
		abspos=1
		shift 1
	else
		abspos=0
	fi

	source utils/configparser.sh
	offset_tilt=$(parse_config "offset_tilt" config_dynamic.ini)
	offset_pan=$(parse_config "offset_pan" config_dynamic.ini)
	reverse_tilt=$(parse_config "reverse_tilt" config_dynamic.ini)

	# check if pan-tilt relay is on
	relay_state=$(python -m hypernets.yocto.relay -g -n2 2>&1 | egrep -o "(True|False)")

	if [[ $relay_state != "True" ]]; then 
		echo  "${red}Relay 2 is off! Turn on to operate pan-tilt${reset}"
		exit -1
	fi

	## read absolute position
	current_abs_pos=$(python -m hypernets.geometry.pan_tilt -g 2>&1 | grep -Eo '[0-9]+([.][0-9]+)?' | paste -s) # pan	tilt
	current_abs_pan=$(cut -f 1 <<< $current_abs_pos)
	current_abs_tilt=$(cut -f 2 <<< $current_abs_pos)

	## calculate relative position
	current_hyper_pan=$(_pt_abs2rel_pan $current_abs_pan)
	current_hyper_tilt=$(_pt_abs2rel_tilt $current_abs_tilt)

	############### print current position #################
	if [[ ${1-} == "" ]]; then
		echo "Current parameters"
		echo "offset_pan = $offset_pan"
		echo "offset_tilt = $offset_tilt"
		echo "reverse_tilt = $reverse_tilt"
		echo
		echo "Current positions"
		printf "abs:   pan = %.1f, tilt = %.1f\n" $current_abs_pan $current_abs_tilt
		printf "hyper: pan = %.1f, tilt = %.1f\n" $current_hyper_pan $current_hyper_tilt
	else ################## go to position ###################
		set +eu
		# check pan and tilt parameters are not empty and are numbers or "x"
		[ -n "$1" ] && [ -n "$2" ] && ( [ "$1" -eq "$1" ] || [[ "$1" == "x" ]] ) 2>/dev/null && ( [ "$2" -eq "$2" ] || [[ "$2" == "x" ]] ) 2>/dev/null
		if [ $? -ne 0 ]; then
			echo "${red}Invalid input, enter pan and tilt values or x if no movement is required.${reset}"
			exit -1
		fi
		set -eu

		## 

		if [[ "$1" == "x" ]]; then ## use current
			requested_abs_pan=$current_abs_pan
		elif [ $abspos = 1 ]; then ## requested abs
			requested_abs_pan="$1"
		else ## requested hyper
			requested_abs_pan=$(_pt_rel2abs_pan "$1")
		fi

		if [[ "$2" == "x" ]]; then ## use current
			requested_abs_tilt=$current_abs_tilt
		elif [ $abspos = 1 ]; then ## requested abs
			requested_abs_tilt="$2"
		else ## requested hyper
			requested_abs_tilt=$(_pt_rel2abs_tilt "$2")
		fi

		## force to 0...360 range
		requested_abs_pan=$( bc <<< "($requested_abs_pan + 36000) % 360" )
		requested_abs_tilt=$( bc <<< "($requested_abs_tilt + 36000) % 360" )
	
		printf "Moving to requested absolute position pan = %.1f, tilt = %.1f\n" $requested_abs_pan $requested_abs_tilt
		python -m hypernets.geometry.pan_tilt -w -p $requested_abs_pan -t $requested_abs_tilt > /dev/null 2>&1

		## read new abs positions
		new_abs_pos=$(python -m hypernets.geometry.pan_tilt -g 2>&1 | grep -Eo '[0-9]+([.][0-9]+)?' | paste -s) # pan	tilt
		new_abs_pan=$(cut -f 1 <<< $new_abs_pos)
		new_abs_tilt=$(cut -f 2 <<< $new_abs_pos)
	
		## calculate relative position
		new_hyper_pan=$(_pt_abs2rel_pan $new_abs_pan)
		new_hyper_tilt=$(_pt_abs2rel_tilt $new_abs_tilt)

		## calculate residuals
		residual_pan=$( bc <<< "$new_abs_pan - $requested_abs_pan" )
		residual_tilt=$( bc <<< "$new_abs_tilt - $requested_abs_tilt" )

		echo
		echo "New positions"
		printf "abs:   pan = %.1f, tilt = %.1f, residuals: pan = %.1f, tilt = %.1f\n" $new_abs_pan $new_abs_tilt $residual_pan $residual_tilt
		printf "hyper: pan = %.1f, tilt = %.1f\n" $new_hyper_pan $new_hyper_tilt
	fi
) # pt()


alias kill-service="sudo systemctl kill --signal=SIGKILL hypernets-sequence"
alias journal="journalctl -b -u hypernets-sequence -e"
alias status="sudo systemctl status hypernets-sequence"
alias gui="(cd $HYPERNETS_TOOLS && python -m hypernets.gui)"
alias runseq="(cd $HYPERNETS_TOOLS && ./utils/run_service.sh)"

# print the help
commands
